### ISSUE TITLE
on_frame_received shall split the checks for name, role, source and target, and do not end session

### ISSUE THREAD

**Issue by ewertons** [Azure/azure-uamqp-c#143] opened 2017-06-21 20:32 UTC
Each of these should give a different error message, and they should not terminate the SESSION.

			if ((attach_get_name(attach_handle, &name) != 0) ||
				(attach_get_role(attach_handle, &role) != 0) ||
				(attach_get_source(attach_handle, &source) != 0) ||
				(attach_get_target(attach_handle, &target) != 0))
			{
				end_session_with_error(session_instance, "amqp:decode-error", "Cannot get link name from ATTACH frame");
			}

**Comment by dcristoloveanu** [comment] 2017-06-21 22:04
Good point, let's split the error messages, I'll issue a fix for it.
With regard to ending the session, actually it seems we have to do it:

"When a session is unable to process input, it MUST indicate this by issuing an END with an appropriate error
indicating the cause of the problem. It MUST then proceed to discard all incoming frames from the remote endpoint
until receiving the remote endpoint’s corresponding end frame."

**Comment by dcristoloveanu** [comment] 2017-06-27 05:42
This is checked in.

**Closed by dcristoloveanu** 2017-06-27 05:42 UTC
