### ISSUE TITLE
Array encoding difficulties

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-uamqp-c#269] opened 2018-10-22 22:45 UTC
Hi @dcristoloveanu - I'm at a bit of a loss and hoping you can help me out here.

So I'm looking at implementing two commands for service bus - both of which deal in arrays.

The first - [Schedule messages](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-request-response#schedule-message) and [cancel scheduled messages](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-request-response#cancel-scheduled-message).

The data flow, in short, is that the response body for the schedule operation will be an AMQP Array of Longs. This is then fed directly into the cancel operation.

However, when I send an Array containing a single long to the service - the service seems to decode it as a different value than that which I sent:
```
AMQP array of sequence numbers to cancel: [69805794325242792]
Error from service: Messages not found. Missing sequence numbers: 101000104

Array as encoded by Service Bus: e00a018100f80000060523a8
Array as encoded by client: e00a018100f80000060523a8
```

If I try the operation using two or more values in the array I get a decode error:
```
AMQP array of sequence numbers to cancel: [40250921740623951, 36028797089964112]
Error from service: The format code '0x50' at frame buffer offset '179' is invalid or unexpected

Array as encoded by Service Bus: e0130281008f0000043b604f8100800000043b6050
Array as encoded by client: e0130281008f0000043b604f8100800000043b6050
```

The second operation is [renew message lock](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-request-response#message-renew-lock).

The data flow in this case is one-way, sending an Array of UUIDs.
Weidly, if I attempt to renew a single lock token, it works:
```
AMQP array of UUID: [ebe26a2f-7c6a-4987-9943-fa04da810029]
Response from the service: {'expirations': [1540248072441]}

Array as encoded by client: e0120198ebe26a2f7c6a49879943fa04da810029
```

But if I attempt to renew 2 or more values in the array, again the decode error:
```
AMQP array of UUID: [4e8c1d72-5b09-4a65-a57c-554edc7a0029, 46fca782-d8cc-439c-a7e9-7d3d0b0d0037]
Error from the service: The format code '0x37' at frame buffer offset '175' is invalid or unexpected

Array as encoded by client: e02302984e8c1d725b094a65a57c554edc7a00299846fca782d8cc439ca7e97d3d0b0d0037
```

I feel that this must be related Array encoding somehow - but the actual byte comparison looks okay. Are there any other areas you can think of that might result in this behaviour? For example the message encoded size calculation?

**Comment by annatisch** [comment] 2018-10-24 16:29
Hi @dcristoloveanu - any thoughts on how I could further debug this?
I've tried comparing each incoming byte of a decoded array to the encoded bytes I'm sending out and can't see anything incriminating....

Any pointers you could give me would be appreciated :)

**Comment by dcristoloveanu** [comment] 2018-10-25 02:44
@annatisch Just got to this, started looking at it, will post what I find shortly.

**Comment by dcristoloveanu** [comment] 2018-10-25 02:57
Hi @annatisch,
Sorry it took so long to get to this.
The issue is due to the fact that arrays in AMQP are monomorphic.
All elements in the array have the same type (the type of the first element).
Thus the constructor is not to be repeated for each value, it should be only one time in the array.

Taking the UUID example above with 2 UUIDs:
e0 <- array constructor
23 <- length of the array
02 <- number of array items
98 <- constructor of the items in the array
4e8c1d725b094a65a57c554edc7a0029 <- UUID value 1
98 <- this constructor is unexpected (service side assumes this to be already part of the 2nd UUID value.
46fca782d8cc439ca7e97d3d0b0d0037

Because of this the service side believes the last 0x37 is unexpected and thus the error.

AMQP spec relevant part: "Array data is encoded as a size and count followed by an array element constructor followed by a monomorphic sequence of values encoded according to the supplied array element constructor"

We missed this in the array encoding implementation and I am sorry for it. This needs a fix in uamqp. Do you want to take a stab or should I? I am good either way, I can carve a bit of time these days if needed.

Cheers!
/Dan

**Comment by annatisch** [comment] 2018-10-25 15:35
Aaaaaaaaaaahhhhhhhhhhhhh thank you thank you thank you! This was driving me insane!! :)
I will try to put together a patch today!

**Comment by annatisch** [comment] 2018-10-25 16:30
Quick question @dcristoloveanu - does that mean for an array of types like binary, string, long etc - that each value in the array must also be of the exact same size as well as type?

**Comment by dcristoloveanu** [comment] 2018-10-25 17:40
The short answer is yes: there is only one constructor that can be for the array items.
I was also thinking of this when I posted the reply.
It makes for some interesting code for encoding the array.

There are 2 choices on the implementation:
1. Always use the constructor that can store the biggest value. Example for an array of uint always use <encoding code="0x70" category="fixed" width="4"
label="32-bit unsigned integer in network byte order"/>
This makes it supposedly easier to implement, but it can waste space on the wire.

2. Look over all elements of the array and determine which constructor should be used. For an uint array, if all elements are width 1 then the constructor for width 1 can be used.

Both implementations have to force the constructor on each of the item (normally each item when encoded will get the optimal constructor). But when encoding arrays, I believe we have to change the encoding functions in uamqp (or add new overloads). The encoding functions (at least for types that have variable length encoding) would need to be able to get an argument to indicate which constructor to use. Then the array encoding can force a certain constructor to be used.

Then the difference between the 1. and 2. choices above is that 2. would have a loop going over the array items and computing which constructor to use.

I am OK with starting with 1. as 2. is an optimization and can easily evolve from 1.

Cheers,
/Dan

**Comment by annatisch** [comment] 2018-10-31 21:39
Quick update - I have this PR ready to go - it's just taken me a little time to actually validate the output against a live service endpoint. Seems to be running now as expected so I will open the PR tomorrow :)

**Comment by annatisch** [comment] 2018-11-01 16:05
I've PR'ed my changes :)

As mentioned in the PR - one area that may need amending is the array size calculation - which probably needs to be reduced to account for the missing constructor bytes in each element....

**Comment by dcristoloveanu** [comment] 2018-11-02 05:41
@annatisch Having a look ...

**Comment by dcristoloveanu** [comment] 2018-11-07 06:56
Merged the PR. You should be set.

**Closed by dcristoloveanu** 2018-11-07 06:56 UTC
